apiVersion: ksquad.io/v1alpha1
kind: Skill
metadata:
  name: dynatrace
spec:
  source:
    type: git
    git:
      repoRef: github.com/dynatrace-oss/dtctl
      ref: 592aaac22c5edda904aacd678fdb9518cb496b6d
      path: skills/dtctl
  permissions:
  - observability:read
  - telemetry:query
  requires:
    toolchains:
    - dtctl@1.0
